services:
  - type: web
    name: bible-summarizer-api
    env: python # Specifies the runtime environment
    region: oregon # Optional: specify a region, e.g., oregon, frankfurt
    plan: free # Keep on the free plan as per original
    
    # Environment variables
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.5" # Specify a recent Python version
      - key: WEB_CONCURRENCY # For Gunicorn: Number of Gunicorn worker processes
        value: "1" # Free tier is limited, 1 worker is safe. Adjust if on a paid plan.
      # Optional: For Hugging Face, though on free tier cache is ephemeral
      # - key: TRANSFORMERS_CACHE
      #   value: "/var/data/hf_cache" # Example path if a persistent disk was available
      # - key: HF_HOME
      #   value: "/var/data/hf_cache"

    # Build command: Installs dependencies
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      
    # Start command: Runs the application using Gunicorn
    # Gunicorn will bind to host 0.0.0.0 and the port specified by Render (PORT env var)
    # app:app refers to the 'app' Flask instance within the 'app.py' file.
    startCommand: gunicorn app:app --timeout 120 # Increased timeout for model download if needed

    # Optional: Health Check (Render does TCP checks by default)
    # healthCheckPath: /api/docs # Or a dedicated /health endpoint
    # autoDeploy: yes # Optional: enable auto-deploys on pushes to the connected Git branch (default is yes)

# Optional: Define databases or other services if needed in the future
# databases:
#   - name: mydatabase
#     plan: free # Example
